include: package:lint/strict.yaml
analyzer:
  exclude:
    - 'build/**'
    - 'mason/build/**'
    - 'mason/feature/**'
    - '**/*.g.dart'
    - '**/*.gr.dart'
    - '**/*.gen.dart'
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
  errors:
    always_require_non_null_named_parameters: error
    annotate_overrides: error
    avoid_catching_errors: error
    avoid_empty_else: error
    avoid_init_to_null: error
    avoid_relative_lib_imports: error
    avoid_renaming_method_parameters: error
    avoid_return_types_on_setters: error
    avoid_returning_null_for_void: error
    await_only_futures: error
    empty_constructor_bodies: error
    no_duplicate_case_values: error
    prefer_contains: error
    prefer_for_elements_to_map_fromIterable: error
    prefer_inlined_adds: error
    prefer_is_not_empty: error
    prefer_iterable_whereType: error
    prefer_spread_collections: error
    recursive_getters: error
    type_init_formals: error
    unnecessary_await_in_return: error
    unnecessary_brace_in_string_interps: error
    unnecessary_new: error
    unnecessary_null_in_if_null_operators: error
    unnecessary_this: error
    valid_regexps: error
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    avoid_positional_boolean_parameters: warning
    avoid_implementing_value_types: warning
    must_be_immutable: warning
    missing_required_param: warning
    missing_return: warning

dart_code_metrics:
  extends:
    - recommended
  rules:
    - avoid-cascade-after-if-null
    - avoid-duplicate-named-imports
    - avoid-unsafe-collection-methods:
        enabled: false
    - avoid-dynamic:
        enabled: false
    - no-empty-block:
        enabled: false
    - unnecessary-trailing-comma:
        enabled: false
    - avoid-shadowing:
        enabled: false
    - avoid-passing-async-when-sync-expected:
        enabled: false
    - avoid-duplicate-initializers:
        enabled: false
    - avoid-missing-image-alt:
        enabled: false
    - avoid-passing-build-context-to-blocs:
        enabled: false
    - avoid-global-state
    - avoid-self-compare
    - avoid-substring
    - avoid-throw-in-catch-block
    - avoid-top-level-members-in-tests
    - binary-expression-operand-order
    - double-literal-format
    - no-boolean-literal-compare
    - no-equal-then-else
    - prefer-enums-by-name
    - prefer-first
    - prefer-immediate-return
    - prefer-iterable-of
    - prefer-last
    - prefer-match-file-name
    - always-remove-listener
    - avoid-border-all
    - avoid-expanded-as-spacer
    - avoid-returning-widgets
    - avoid-shrink-wrap-in-lists
    - avoid-wrapping-in-padding
    - check-for-equals-in-render-object-setters
    - prefer-const-border-radius
    - prefer-correct-edge-insets-constructor
    - prefer-text-rich
    - avoid-bloc-public-fields
    - avoid-bloc-public-methods
    - avoid-cubits
    - avoid-duplicate-bloc-event-handlers
    - avoid-empty-build-when
    - avoid-existing-instances-in-bloc-provider
    - avoid-instantiating-in-bloc-value-provider
    - avoid-passing-bloc-to-bloc
    - avoid-returning-value-from-cubit-methods
    - emit-new-bloc-state-instances
    - handle-bloc-event-subclasses
    - prefer-bloc-event-suffix
    - prefer-bloc-extensions
    - prefer-bloc-state-suffix
    - prefer-correct-bloc-provider
    - prefer-immutable-bloc-events
    - prefer-immutable-bloc-state
    - prefer-multi-bloc-provider
    - prefer-sealed-bloc-events
    - prefer-sealed-bloc-state

linter:
  rules:
    require_trailing_commas: true
    avoid_empty_else: true
    avoid_relative_lib_imports: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    prefer_single_quotes: true
    collection_methods_unrelated_type: true
    curly_braces_in_flow_control_structures: true
    dangling_library_doc_comments: true
    depend_on_referenced_packages: true
    empty_catches: true
    file_names: true
    hash_and_equals: true
    implicit_call_tearoffs: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_check_on_nullable_type_parameter: true
    package_prefixed_library_names: true
    prefer_generic_function_type_aliases: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_iterable_whereType: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    secure_pubspec_urls: true
    type_literal_in_constant_pattern: true
    unnecessary_overrides: true
    unrelated_type_equality_checks: true
    use_string_in_part_of_directives: true
    valid_regexps: true
    void_checks: true
    annotate_overrides: true
    avoid_function_literals_in_foreach_calls: true
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_single_cascade_in_expression_statements: true
    constant_identifier_names: true
    control_flow_in_finally: true
    empty_constructor_bodies: true
    empty_statements: true
    exhaustive_cases: true
    implementation_imports: true
    library_names: true
    library_prefixes: true
    library_private_types_in_public_api: true
    no_leading_underscores_for_library_prefixes: true
    no_leading_underscores_for_local_identifiers: true
    null_closures: true
    overridden_fields: true
    package_names: true
    prefer_adjacent_string_concatenation: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_contains: true
    prefer_final_fields: true
    prefer_for_elements_to_map_fromIterable: true
    prefer_function_declarations_over_variables: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_not_operator: true
    prefer_null_aware_operators: true
    prefer_spread_collections: true
    recursive_getters: true
    slash_for_doc_comments: true
    type_init_formals: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_constructor_name: true
    unnecessary_getters_setters: true
    unnecessary_late: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    unnecessary_to_list_in_spreads: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_super_parameters: true
    always_declare_return_types: true
    always_require_non_null_named_parameters: true
    always_use_package_imports: true
    avoid_bool_literals_in_conditional_expressions: true
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false
    avoid_redundant_argument_values: false
    avoid_dynamic_calls: false
    use_test_throws_matchers: false
    use_build_context_synchronously: false
    unreachable_from_main: false
    unnecessary_library_directive: false
    prefer_null_aware_method_calls: false
    noop_primitive_operations: false
    deprecated_consistency: false
