name: kosmos_chat
description: A new Flutter package project.
version: 2.0.0
homepage: none
publish_to: none

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core:
  cloud_firestore:
  firebase_core_platform_interface:
  firebase_auth:
  firebase_database:
  cloud_functions:
  firebase_storage:
  firebase_messaging:
  flutter_sound:
  geocoding:

  gesture_x_detector:
  sliver_tools:
  freezed_annotation:
  json_annotation:
  image_painter: 0.6.1
  flutter_riverpod: 2.6.1
  record:
  just_audio:
  audioplayers:
  audio_waveforms: 
  camerawesome: 
  permission_handler:

  hive:
  hive_flutter:
  path_provider:

  scrollable_positioned_list:
  flutter_staggered_animations:
  cached_network_image:
  hooks_riverpod:
  flutter_svg:
  uuid:
  flutter_slidable:
  shimmer:
  emoji_picker_flutter:
  flutter_isolate:

  sticky_headers:

  # Media managing
  photo_manager:
  wechat_assets_picker:
  video_player:
  chewie:
  photo_view:
  wechat_camera_picker:
  timeago_flutter:
  image_gallery_saver_plus: ^4.0.1
  core_kosmos:
    path: ../core_kosmos

  ui_kosmos_v4:
    path: ../ui_kosmos_v4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:

  json_serializable:
  freezed:
  build_runner:

flutter:
  assets:
    - assets/svg/
    - assets/images/
