// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm7lbqU3VmDKUimAdyx8uanU9A3cLvU5o',
    appId: '1:1062855309544:android:d64c3416b8bde94970f15d',
    messagingSenderId: '1062855309544',
    projectId: 'klozy-836c3',
    databaseURL:
        'https://klozy-836c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'klozy-836c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhnL0HzqM2KV2ANq8SfrFQ25d5OLa9JY4',
    appId: '1:1062855309544:ios:146dc605027d928770f15d',
    messagingSenderId: '1062855309544',
    projectId: 'klozy-836c3',
    databaseURL:
        'https://klozy-836c3-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'klozy-836c3.firebasestorage.app',
    iosClientId:
        '1062855309544-sl6upanfgjgb7hd1dlqvh8vv93duhb5s.apps.googleusercontent.com',
    iosBundleId: 'com.klozy.app',
  );
}
